name: Auto Pull Request
on:
  push:
    branches:
      - 'develop'
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create Pull Request
        uses: diillson/auto-pull-request@v1.0.1
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}

