name: Deploy Azure Resources
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
#   schedule:
#     - cron: '0 0 * * *' # Every day at midnight UTC
#   workflow_dispatch:
#     inputs:
#       environment:
#         description: 'Environment to deploy to'
#         required: true
#         default: 'test'

on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

env:
    AZURE_RESOURCEGROUP_NAME: rg-uks-prod-github
    ENVIRONMENT: test

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Bicep linter
      run: az bicep build --file deploy/main.bicep
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Validate Bicep
        uses: azure/bicep-deploy@v2
        with:
         type: deployment
         operation: validate
         name: Validate
         scope: resourceGroup
         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
         deployment-name: ${{ github.run_number }}
         resource-group-name: ${{ env.AZURE_RESOURCEGROUP_NAME }}
         template: deploy/main.bicep
         parameters-file: deploy/main.bicepparam

      - name: Logout from Azure
        run: az logout
  whatif:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Whatif Bicep
        uses: azure/bicep-deploy@v2
        with:
         type: deployment
         operation: whatIf
         name: whatIf
         scope: resourceGroup
         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
         deployment-name: ${{ github.run_number }}
         resource-group-name: ${{ env.AZURE_RESOURCEGROUP_NAME }}
         template: deploy/main.bicep
         parameters-file: deploy/main.bicepparam

      - name: Logout from Azure
        run: az logout
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Bicep
        uses: azure/bicep-deploy@v2
        with:
         type: deployment
         operation: create
         name: create
         scope: resourceGroup
         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
         deployment-name: ${{ github.run_number }}
         resource-group-name: ${{ env.AZURE_RESOURCEGROUP_NAME }}
         template: deploy/main.bicep
         parameters-file: deploy/main.bicepparam

      - name: Logout from Azure
        run: az logout         