name: MyWorkflow

on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

env:
    AZURE_RESOURCEGROUP_NAME: rg-uks-prod-github
    ENVIRONMENT: nonprod

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Bicep linter
      run: az bicep build --file deploy/main.bicep
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up Azure CLI
      #   uses: azure/setup-azure@v2
      #   with:
      #     azure-cli-version: '2.30.0'

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Validate Bicep
        uses: azure/bicep-deploy@v2
        with:
         type: deployment
         operation: validate
         name: Validate
         scope: resourceGroup
         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
         deployment-name: ${{ github.run_number }}
         resource-group-name: ${{ env.AZURE_RESOURCEGROUP_NAME }}
         template: deploy/main.bicep
         parameters-file: deploy/main.bicepparam

      - name: Logout from Azure
        run: az logout
  whatif:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up Azure CLI
      #   uses: azure/setup-azure@v2
      #   with:
      #     azure-cli-version: '2.30.0'

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Whatif Bicep
        uses: azure/bicep-deploy@v2
        with:
         type: deployment
         operation: whatif
         name: Validate
         scope: resourceGroup
         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
         deployment-name: ${{ github.run_number }}
         resource-group-name: ${{ env.AZURE_RESOURCEGROUP_NAME }}
         template: deploy/main.bicep
         parameters-file: deploy/main.bicepparam

      - name: Logout from Azure
        run: az logout    
    # runs-on: ubuntu-latest
    # steps:
    # - uses: azure/bicep-deploy@v2
    # - name: Run preflight validation
    #   with:
    #     type: deployment
    #     operation: validate
    #     name: Validate
    #     location: uksouth
    #     scope: subscription
    #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    #     template-file: deploy/main.bicep
    #     parameters-file: deploy/main.bicepparam
         #  - uses: actions/checkout@v3
  # #  - uses: azure/login@v2
  # validate:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: azure/login@v2
  #     name: Sign in to Azure
  #     with:
  #       client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #       tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #       subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #   - uses: azure/bicep-deploy@v2
  #     name: Run preflight validation
  #     with:
  #       deploymentName: ${{ github.run_number }}
  #       resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
  #       template: deploy/main.bicep
  #       parameters: deploy/main.bicepparam
  #       deploymentMode: Validate
  #       - name: Deployment
  # uses: azure/bicep-deploy@v2
  # with:
  #   type: deployment
  #   operation: create
  #   name: Development
  #   location: westus2
  #   scope: subscription
  #   subscription-id: 00000000-0000-0000-0000-000000000000
  #   template-file: ./main.bicep
  #   parameters-file: ./main.bicepparam
  # preview: 
  #   runs-on: ubuntu-latest
  #   needs: [lint, validate]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: azure/login@v2
  #       name: Sign into azure
  #       with:
  #         client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #     - uses: azure/bicep-deploy@v2
  #       name: Run what-if
  #       with:
  #         failOnStdErr: false
  #         resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
  #         template: deploy/main.bicep
  #         parameters: deploy/main.bicepparam
  #         additionalArguments: --what-if
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: preview
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: azure/login@v2
  #       name: Sign in to azure
  #       with:
  #         client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #     - uses: azure/bicep-deploy@v2
  #       name: Deploy vm
  #       with:
  #         failOnStdError: false
  #         deploymentName: ${{ github.run_number }}
  #         resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
  #         template: deploy/main.bicep
  #         paramaters: deploy/main.bicepparam
    # steps:
    # - uses: actions/checkout@v3
    #   with:
    #     path: repo
    # - uses: azure/login@v2
    #   with:
    #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
    #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    # - uses: azure/arm-deploy@v2
    #   with:
    #     resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
    #     template: ./deploy/main.bicep
    #     parameters: ./deploy/main.bicepparam